name: axe check

on:
  pull_request:
    branches: [main]

jobs:
  axe-check:
    name: axe check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:4200
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:4200 --exit
