name: Build check

on:
  pull_request:
    branches: [main]

jobs:
  build-check:
    name: Build check
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [18]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: instal dependencies
        run: npm ci

      - name: build application
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          all: 'true'
