name: Build check

on:
  pull_request:
    branches: [main]

jobs:
  build-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install
        run: npm ci

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          all: 'true'
