name: E2E tests

on:
  pull_request:
    branches: [main]

jobs:
  e2e-test:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: npm ci

      - name: run e2e tests
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: e2e-tests
          all: 'true'
