name: Format & Lint check

on:
  pull_request:
    branches: [main]

jobs:
  format-and-lint-check:
    name: Format & Lint check
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: npm install
        run: npm ci

      - name: run linter
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: format:check, lint
          all: 'true'
          parallel: 1
