name: Lighthouse

on:
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: npm install, build
        run: npm ci

      - name: build application
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          all: 'true'

      - name: run Lighthouse CI
        run: npm start & npx wait-on http://localhost:4200
      - run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun --collect.url=http://localhost:4200 --assert.preset=lighthouse:recommended --upload.token
