name: Lighthouse

on:
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun
