name: Lint check

on:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm install
        run: npm ci

      - name: install lint
        run: npm i --save-dev @nx/eslint

      - name: lint check
        run: nx lint myorg
