name: pa11y
on:
  pull_request:
    branches: [main]

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - run: npm run build --if-present

      - run: npm start & npx wait-on http://localhost:3000

      - name: Run pa11y
        run: |
          npm install -g pa11y
          pa11y http://localhost:3000
