name: Sonar check

on:
  pull_request:
    branches: [main]

jobs:
  sonar-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: run sonar check
        run: npm run sonar
