name: Sonar scan

on:
  pull_request:
    branches: [main]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm ci
